export const data = [
  {
    projectName: "Système de Gestion de Stock",
    taskName: "Développer une fonction de connexion utilisateur",
    publicationDate: "2024-03-15",
    deadline: "2024-03-25",
    status: "en cours",
    service: "Développement",
    comment: "Tâche en cours, avancement satisfaisant.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Optimiser les requêtes SQL",
    publicationDate: "2024-03-10",
    deadline: "2024-03-20",
    status: "validé",
    service: "Infrastructure",
    comment: "Tâche terminée avec succès.",
  },
  {
    projectName: "Système de Gestion de Stock",
    taskName: "Déployer le système de paiement",
    publicationDate: "2024-03-18",
    deadline: "2024-03-28",
    status: "en cours",
    service: "Développement",
    comment: "En attente de validation de l'API tierce.",
  },
  {
    projectName: "Plateforme de Réservation de Voyages",
    taskName: "Configurer le serveur de production",
    publicationDate: "2024-03-12",
    deadline: "2024-03-22",
    status: "refusé",
    service: "Infrastructure",
    comment: "Problèmes de compatibilité détectés, en attente de résolution.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Créer une documentation pour l'API",
    publicationDate: "2024-03-08",
    deadline: "2024-03-18",
    status: "validé",
    service: "Documentation",
    comment: "Documentation finalisée et partagée avec l'équipe.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Optimiser les requêtes SQL",
    publicationDate: "2024-03-10",
    deadline: "2024-03-20",
    status: "validé",
    service: "Infrastructure",
    comment: "Tâche terminée avec succès.",
  },
  {
    projectName: "Système de Gestion de Stock",
    taskName: "Déployer le système de paiement",
    publicationDate: "2024-03-18",
    deadline: "2024-03-28",
    status: "en cours",
    service: "Développement",
    comment: "En attente de validation de l'API tierce.",
  },
  {
    projectName: "Plateforme de Réservation de Voyages",
    taskName: "Configurer le serveur de production",
    publicationDate: "2024-03-12",
    deadline: "2024-03-22",
    status: "refusé",
    service: "Infrastructure",
    comment: "Problèmes de compatibilité détectés, en attente de résolution.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Créer une documentation pour l'API",
    publicationDate: "2024-03-08",
    deadline: "2024-03-18",
    status: "validé",
    service: "Documentation",
    comment: "Documentation finalisée et partagée avec l'équipe.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Optimiser les requêtes SQL",
    publicationDate: "2024-03-10",
    deadline: "2024-03-20",
    status: "validé",
    service: "Infrastructure",
    comment: "Tâche terminée avec succès.",
  },
  {
    projectName: "Système de Gestion de Stock",
    taskName: "Déployer le système de paiement",
    publicationDate: "2024-03-18",
    deadline: "2024-03-28",
    status: "en cours",
    service: "Développement",
    comment: "En attente de validation de l'API tierce.",
  },
  {
    projectName: "Plateforme de Réservation de Voyages",
    taskName: "Configurer le serveur de production",
    publicationDate: "2024-03-12",
    deadline: "2024-03-22",
    status: "refusé",
    service: "Infrastructure",
    comment: "Problèmes de compatibilité détectés, en attente de résolution.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Créer une documentation pour l'API",
    publicationDate: "2024-03-08",
    deadline: "2024-03-18",
    status: "validé",
    service: "aaa",
    comment: "Documentation finalisée et partagée avec l'équipe.",
  },
  {
    projectName: "Système de Gestion de Stock",
    taskName: "Déployer le système de paiement",
    publicationDate: "2024-03-18",
    deadline: "2024-03-28",
    status: "en cours",
    service: "Développement",
    comment: "En attente de validation de l'API tierce.",
  },
  {
    projectName: "Plateforme de Réservation de Voyages",
    taskName: "Configurer le serveur de production",
    publicationDate: "2024-03-12",
    deadline: "2024-03-22",
    status: "refusé",
    service: "Infrastructure",
    comment: "Problèmes de compatibilité détectés, en attente de résolution.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Créer une documentation pour l'API",
    publicationDate: "2024-03-08",
    deadline: "2024-03-18",
    status: "validé",
    service: "Documentation",
    comment: "Documentation finalisée et partagée avec l'équipe.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Optimiser les requêtes SQL",
    publicationDate: "2024-03-10",
    deadline: "2024-03-20",
    status: "validé",
    service: "Infrastructure",
    comment: "Tâche terminée avec succès.",
  },
  {
    projectName: "Système de Gestion de Stock",
    taskName: "Déployer le système de paiement",
    publicationDate: "2024-03-18",
    deadline: "2024-03-28",
    status: "en cours",
    service: "Développement",
    comment: "En attente de validation de l'API tierce.",
  },
  {
    projectName: "Plateforme de Réservation de Voyages",
    taskName: "Configurer le serveur de production",
    publicationDate: "2024-03-12",
    deadline: "2024-03-22",
    status: "refusé",
    service: "Infrastructure",
    comment: "Problèmes de compatibilité détectés, en attente de résolution.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Créer une documentation pour l'API",
    publicationDate: "2024-03-08",
    deadline: "2024-03-18",
    status: "validé",
    service: "aaa",
    comment: "Documentation finalisée et partagée avec l'équipe.",
  },
  {
    projectName: "Système de Gestion de Stock",
    taskName: "Déployer le système de paiement",
    publicationDate: "2024-03-18",
    deadline: "2024-03-28",
    status: "en cours",
    service: "Développement",
    comment: "En attente de validation de l'API tierce.",
  },
  {
    projectName: "Plateforme de Réservation de Voyages",
    taskName: "Configurer le serveur de production",
    publicationDate: "2024-03-12",
    deadline: "2024-03-22",
    status: "refusé",
    service: "Infrastructure",
    comment: "Problèmes de compatibilité détectés, en attente de résolution.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Créer une documentation pour l'API",
    publicationDate: "2024-03-08",
    deadline: "2024-03-18",
    status: "validé",
    service: "Documentation",
    comment: "Documentation finalisée et partagée avec l'équipe.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Optimiser les requêtes SQL",
    publicationDate: "2024-03-10",
    deadline: "2024-03-20",
    status: "validé",
    service: "Infrastructure",
    comment: "Tâche terminée avec succès.",
  },
  {
    projectName: "Système de Gestion de Stock",
    taskName: "Déployer le système de paiement",
    publicationDate: "2024-03-18",
    deadline: "2024-03-28",
    status: "en cours",
    service: "Développement",
    comment: "En attente de validation de l'API tierce.",
  },
  {
    projectName: "Plateforme de Réservation de Voyages",
    taskName: "Configurer le serveur de production",
    publicationDate: "2024-03-12",
    deadline: "2024-03-22",
    status: "refusé",
    service: "Infrastructure",
    comment: "Problèmes de compatibilité détectés, en attente de résolution.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Créer une documentation pour l'API",
    publicationDate: "2024-03-08",
    deadline: "2024-03-18",
    status: "validé",
    service: "aaa",
    comment: "Documentation finalisée et partagée avec l'équipe.",
  },
  {
    projectName: "Système de Gestion de Stock",
    taskName: "Déployer le système de paiement",
    publicationDate: "2024-03-18",
    deadline: "2024-03-28",
    status: "en cours",
    service: "Développement",
    comment: "En attente de validation de l'API tierce.",
  },
  {
    projectName: "Plateforme de Réservation de Voyages",
    taskName: "Configurer le serveur de production",
    publicationDate: "2024-03-12",
    deadline: "2024-03-22",
    status: "refusé",
    service: "Infrastructure",
    comment: "Problèmes de compatibilité détectés, en attente de résolution.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Créer une documentation pour l'API",
    publicationDate: "2024-03-08",
    deadline: "2024-03-18",
    status: "validé",
    service: "Documentation",
    comment: "Documentation finalisée et partagée avec l'équipe.",
  },
  {
    projectName: "Plateforme de Commerce Électronique",
    taskName: "Optimiser les requêtes SQL",
    publicationDate: "2024-03-10",
    deadline: "2024-03-20",
    status: "validé",
    service: "Infrastructure",
    comment: "Tâche terminée avec succès.",
  },
  {
    projectName: "Système de Gestion de Stock",
    taskName: "Déployer le système de paiement",
    publicationDate: "2024-03-18",
    deadline: "2024-03-28",
    status: "en cours",
    service: "Développement",
    comment: "En attente de validation de l'API tierce.",
  },
  {
    projectName: "Plateforme de Réservation de Voyages",
    taskName: "Configurer le serveur de production",
    publicationDate: "2024-03-12",
    deadline: "2024-03-22",
    status: "refusé",
    service: "Infrastructure",
    comment: "Problèmes de compatibilité détectés, en attente de résolution.",
  },
  {
    projectName: "Omouri",
    taskName: "Créer une documentation pour l'API",
    publicationDate: "2024-03-08",
    deadline: "2024-03-18",
    status: "validé",
    service: "bbb",
    comment: "AADocumentation finalisée et partagée avec l'équipe.",
  },
];
